### ISSUE TITLE
JSON Standard Conformance

### ISSUE THREAD

**Issue by LloydThinks** [OpenReqEU/eclipse-issue-prioritizer#3]
Please review your application for JSON Standard Conformance and comment on the OpenSource Compliance Checklist once you have updated your application to be conformant. Alternatively, you may also decide that your application does not need JSON Standard Conformance, and you may also comment that.

(Links to the JSON Standard Conformance and OpenSource Compliance Checklist left out because they are not for public consumption)

Lloyd

**Comment by jnerlich** [comment]
Document updated.

**Comment by jnerlich** [comment]
@LloydThinks could you please specify why you reopened this issue?

**Comment by LloydThinks** [comment]
The issue is not reopened. We are cleaning up Github Issues with assignees, labels, etc.
